services:
  web:
    hostname: web
    build:
      context: ./php
      dockerfile: ./dockerfile
      args:
        - USERNAME=${USERNAME:-ubuntu}
        - GROUPNAME=${GROUPNAME:-ubuntu}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/ssl.conf:/etc/apache2/mods-available/ssl.conf
      - ./myca:/etc/ssl/myca
      - ./scripts:/scripts
      - ./.env:/.env
    ports:
      - ${WEB_HTTP_PORT:-80}:80
      - ${WEB_HTTPS_PORT:-443}:443
    # extra_hosts:
    #   - ${WEB_HOST_NAME:-webcontainer.dev.internal}:127.0.0.1
    env_file:
      .env

  mail:
    hostname: smtp4dev
    image: rnwood/smtp4dev:v3.1
    ports:
      - '${SMTP4DEV_ADMIN_PORT:-5000}:80'
    volumes:
      - ./smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__BasePath=/smtp4dev
