services:
  web:
    depends_on:
      - mysql

  mysql:
    hostname: mysql
    image: mysql:8.0
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./mysql_ex:/ex
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
