version: '3.7'

services:
  web:
    hostname: web
    build:
      context: ./php
      dockerfile: ./dockerfile
      args:
        - USERNAME=${USERNAME:-ubuntu}
        - GROUPNAME=${GROUPNAME:-ubuntu}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./html:/var/www/html
      # - ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./php/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - ./php/conf/ssl.conf:/etc/apache2/mods-available/ssl.conf
      - ./php/ssl/myca:/etc/ssl/myca
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"
    depends_on:
      # - postgres
      - mysql
    extra_hosts:
      - dev.internal:127.0.0.1

  # postgres:
  #   image: postgres:11
  #   volumes:
  #     - ./postgres_db:/var/lib/postgresql/data
  #     - ./postgres_ex:/ex
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"

  mysql:
    hostname: mysql
    image: mysql:5.7
    volumes:
      - ./mysql_db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}

  mail:
    hostname: mailhog
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT:-1025}:1025
      - ${MAILHOG_FRONT_PORT:-8025}:8025