services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./myca/:/etc/nginx/certs
    ports:
      - '443:443'
      - '80:80'
      - '5173:5173'
    environment:
      DEV_NGINX_SERVER_NAME: '${WEB_HOST_NAME:-localhost}'
      DEV_NGINX_PROXY_PASS: 'web'

  web:
    hostname: web
    build:
      context: ./php-apache
      dockerfile: ./dockerfile
      args:
        - USERNAME=${USERNAME:-ubuntu}
        - GROUPNAME=${GROUPNAME:-ubuntu}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./html:/var/www/html
      - ./html_default:/var/www/html_default
      - ./php-apache/php.ini:/usr/local/etc/php/php.ini
      - ./php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./scripts:/scripts
      - ./.env:/.env_file
    extra_hosts:
      - ${WEB_HOST_NAME:-webcontainer.dev.internal}:127.0.0.1
    env_file:
      .env

  mail:
    hostname: smtp4dev
    image: rnwood/smtp4dev:v3.1
    ports:
      - '${SMTP4DEV_ADMIN_PORT:-5000}:80'
    volumes:
      - ./smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__BasePath=/smtp4dev
